export default [
    { "url": "https://opentdb.com/api.php?amount=6&category=9&difficulty=easy&type=multiple", "title":"general" },
    { "url": "https://opentdb.com/api.php?amount=6&category=10&difficulty=easy&type=multiple", "title": "books" },
    { "url": "https://opentdb.com/api.php?amount=6&category=11&difficulty=easy&type=multiple", "title": "film" },
    { "url": "https://opentdb.com/api.php?amount=6&category=12&difficulty=easy&type=multiple", "title": "music" },
    { "url": "https://opentdb.com/api.php?amount=6&category=13&difficulty=easy&type=multiple", "title": "theater" },
    { "url": "https://opentdb.com/api.php?amount=6&category=14&difficulty=easy&type=multiple", "title": "TV" },
    { "url": "https://opentdb.com/api.php?amount=6&category=15&difficulty=easy&type=multiple", "title": "Video games" },
    { "url": "https://opentdb.com/api.php?amount=6&category=16&difficulty=easy&type=multiple", "title": "board games" },
    { "url": "https://opentdb.com/api.php?amount=6&category=17&difficulty=easy&type=multiple", "title": "Science & nature" },
    { "url": "https://opentdb.com/api.php?amount=6&category=18&difficulty=easy&type=multiple", "title": "computers" },
    { "url": "https://opentdb.com/api.php?amount=6&category=19&difficulty=easy&type=multiple", "title": "Mathematics" },
    { "url": "https://opentdb.com/api.php?amount=6&category=20&difficulty=easy&type=multiple", "title": "Mythology" },
    { "url": "https://opentdb.com/api.php?amount=6&category=21&difficulty=easy&type=multiple", "title": "Sports" },
    { "url": "https://opentdb.com/api.php?amount=6&category=22&difficulty=easy&type=multiple", "title": "Geography" },
    { "url": "https://opentdb.com/api.php?amount=6&category=23&difficulty=easy&type=multiple", "title": "History" },
    { "url": "https://opentdb.com/api.php?amount=6&category=24&difficulty=easy&type=multiple", "title": "Politics" },
    { "url": "https://opentdb.com/api.php?amount=6&category=25&difficulty=easy&type=multiple", "title": "Art" },
    { "url": "https://opentdb.com/api.php?amount=6&category=26&difficulty=easy&type=multiple", "title": "Celebrities" },
    { "url": "https://opentdb.com/api.php?amount=6&category=27&difficulty=easy&type=multiple", "title": "Animals" },
    { "url": "https://opentdb.com/api.php?amount=6&category=28&difficulty=easy&type=multiple", "title": "Vehicles" },
    { "url": "https://opentdb.com/api.php?amount=6&category=29&difficulty=easy&type=multiple", "title": "Comics" },
    { "url": "https://opentdb.com/api.php?amount=6&category=30&difficulty=easy&type=multiple", "title": "Gadgets" },
    { "url": "https://opentdb.com/api.php?amount=6&category=31&difficulty=easy&type=multiple", "title": "Anime & manga" },
    { "url": "https://opentdb.com/api.php?amount=6&category=32&difficulty=easy&type=multiple", "title": "Cartoons & animation" }
]